export const CREATE_PRODUCT_REQUST = 'CREATE_PRODUCT_REQUST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';

export const FETCH_PRODUCTS_REQUST = 'FETCH_PRODUCTS_REQUST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const LOAD_MORE_PRODUCTS_REQUST = 'LOAD_MORE_PRODUCTS_REQUST';
export const LOAD_MORE_PRODUCTS_SUCCESS = 'LOAD_MORE_PRODUCTS_SUCCESS';
export const LOAD_MORE_PRODUCTS_FAILURE = 'LOAD_MORE_PRODUCTS_FAILURE';

export const FETCH_PRODUCT_BY_ID = 'FETCH_PRODUCT_BY_ID';

export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET';
export const REMOVE_PRODUCT_FROM_BASKET = 'REMOVE_PRODUCT_FROM_BASKET';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const CLEAN_BASKET = 'CLEAN_BASKET';

export const GET_PATH_PICTURE = 'GET_PATH_PICTURE';
